steps:
- checkout: self
  clean: true
  fetchDepth: 5

#- script: ./configure --with-pydebug --with-openssl=/usr/local/opt/openssl --prefix=/opt/python-azdev
- script: ./configure --with-pydebug --with-openssl=/usr/local/opt/openssl --prefix=./python-azdev
  displayName: 'Configure CPython (debug)'

- script: make -j4
  displayName: 'Build CPython'

- script: make pythoninfo
  displayName: 'Display build info'

- script: make buildbottest TESTOPTS="-j4 -uall,-cpu --junit-xml=$(build.binariesDirectory)/test-results.xml"
  displayName: 'Tests'
  continueOnError: true
  timeoutInMinutes: 30

- task: PublishTestResults@2
  displayName: 'Publish Test Results'
  inputs:
    testResultsFiles: '$(build.binariesDirectory)/test-results.xml'
    mergeTestResults: true
    testRunTitle: $(testRunTitle)
    platform: $(testRunPlatform)
  condition: succeededOrFailed()



- script: cp -r * $(Build.StagingDirectory)
  displayName: 'Copy all to artifact directory'

- task: PublishPipelineArtifact@1 
  inputs:
    path: "$(Build.ArtifactStagingDirectory)"
    artifact: artifact-py-macOSX
